#!/usr/bin/env python3
# -*- coding: utf-8 -*-

DEBUG = False

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 31536000
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_AGE = 43200
SESSION_COOKIE_SECURE = True
